/*
 * Copyright © Siemens 2020 - 2025. ALL RIGHTS RESERVED.
 * Licensed under the MIT license
 * See LICENSE file in the top-level directory
 */

//
// Copyright © Siemens 2020 - 2025. ALL RIGHTS RESERVED.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.6
// source: System.proto

package siemens_iedge_dmapi_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ModelNumber type indicates device specific model information.
type ModelNumber struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelNumber   string                 `protobuf:"bytes,1,opt,name=modelNumber,proto3" json:"modelNumber,omitempty"` // Can be MLFB for SIEMENS devices, for 3rd party vendors it can be any model information.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelNumber) Reset() {
	*x = ModelNumber{}
	mi := &file_System_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelNumber) ProtoMessage() {}

func (x *ModelNumber) ProtoReflect() protoreflect.Message {
	mi := &file_System_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelNumber.ProtoReflect.Descriptor instead.
func (*ModelNumber) Descriptor() ([]byte, []int) {
	return file_System_proto_rawDescGZIP(), []int{0}
}

func (x *ModelNumber) GetModelNumber() string {
	if x != nil {
		return x.ModelNumber
	}
	return ""
}

// FirmwareInfo contains Firmware Version.
type FirmwareInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"` // Firmware version.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirmwareInfo) Reset() {
	*x = FirmwareInfo{}
	mi := &file_System_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirmwareInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirmwareInfo) ProtoMessage() {}

func (x *FirmwareInfo) ProtoReflect() protoreflect.Message {
	mi := &file_System_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirmwareInfo.ProtoReflect.Descriptor instead.
func (*FirmwareInfo) Descriptor() ([]byte, []int) {
	return file_System_proto_rawDescGZIP(), []int{1}
}

func (x *FirmwareInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// System Resource , memory or storage.
type Resource struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	TotalSpaceInGB            float32                `protobuf:"fixed32,1,opt,name=totalSpaceInGB,proto3" json:"totalSpaceInGB,omitempty"`                       // Total capacity of storage device in Gigabytes e.g: 3.5
	FreeSpaceInGB             float32                `protobuf:"fixed32,2,opt,name=freeSpaceInGB,proto3" json:"freeSpaceInGB,omitempty"`                         // Free space of storage device in Gigabytes e.g: 40.4
	UsedSpaceInGB             float32                `protobuf:"fixed32,3,opt,name=usedSpaceInGB,proto3" json:"usedSpaceInGB,omitempty"`                         // Used space of storage device in Gigabytes e.g: 23.2
	PercentageFreeSpace       float32                `protobuf:"fixed32,4,opt,name=percentageFreeSpace,proto3" json:"percentageFreeSpace,omitempty"`             // Percentage of available space e.g: 3.5
	PercentageUsedSpace       float32                `protobuf:"fixed32,5,opt,name=percentageUsedSpace,proto3" json:"percentageUsedSpace,omitempty"`             // Percentage of used space e.g: 96.5
	DiskType                  string                 `protobuf:"bytes,6,opt,name=diskType,proto3" json:"diskType,omitempty"`                                     // Type of disk eg: "HDD" or "SSD" or "EMMC"
	DiskTotalReadSectorsInMB  float32                `protobuf:"fixed32,7,opt,name=diskTotalReadSectorsInMB,proto3" json:"diskTotalReadSectorsInMB,omitempty"`   // Total number of sectors read successfully in Megabytes e.g: 58.9
	DiskTotalWriteSectorsInMB float32                `protobuf:"fixed32,8,opt,name=diskTotalWriteSectorsInMB,proto3" json:"diskTotalWriteSectorsInMB,omitempty"` // Total number of sectors written successfully in Megabytes e.g: 32.7
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_System_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_System_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_System_proto_rawDescGZIP(), []int{2}
}

func (x *Resource) GetTotalSpaceInGB() float32 {
	if x != nil {
		return x.TotalSpaceInGB
	}
	return 0
}

func (x *Resource) GetFreeSpaceInGB() float32 {
	if x != nil {
		return x.FreeSpaceInGB
	}
	return 0
}

func (x *Resource) GetUsedSpaceInGB() float32 {
	if x != nil {
		return x.UsedSpaceInGB
	}
	return 0
}

func (x *Resource) GetPercentageFreeSpace() float32 {
	if x != nil {
		return x.PercentageFreeSpace
	}
	return 0
}

func (x *Resource) GetPercentageUsedSpace() float32 {
	if x != nil {
		return x.PercentageUsedSpace
	}
	return 0
}

func (x *Resource) GetDiskType() string {
	if x != nil {
		return x.DiskType
	}
	return ""
}

func (x *Resource) GetDiskTotalReadSectorsInMB() float32 {
	if x != nil {
		return x.DiskTotalReadSectorsInMB
	}
	return 0
}

func (x *Resource) GetDiskTotalWriteSectorsInMB() float32 {
	if x != nil {
		return x.DiskTotalWriteSectorsInMB
	}
	return 0
}

// Cpu type contains Cpu utilization at the current moment.
type Cpu struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UsedCpuPercentage float32                `protobuf:"fixed32,1,opt,name=usedCpuPercentage,proto3" json:"usedCpuPercentage,omitempty"` // Percentage of used CPU e.g: 20.0
	FreeCpuPercentage float32                `protobuf:"fixed32,2,opt,name=freeCpuPercentage,proto3" json:"freeCpuPercentage,omitempty"` // Percentage of available CPU e.g: 80.0
	CoreCount         int32                  `protobuf:"varint,3,opt,name=coreCount,proto3" json:"coreCount,omitempty"`                  // Total available core count for CPU.e.g  2C/4T CPU value will be 4
	ModelInfo         string                 `protobuf:"bytes,4,opt,name=modelInfo,proto3" json:"modelInfo,omitempty"`                   // intel x64 etc..
	IdleTime          float64                `protobuf:"fixed64,5,opt,name=idleTime,proto3" json:"idleTime,omitempty"`                   // Idle time of CPU eg: 3662.50 (in seconds)
	Frequency         float64                `protobuf:"fixed64,6,opt,name=frequency,proto3" json:"frequency,omitempty"`                 // Frequency of CPU eg: 2495.999 (in MHz)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Cpu) Reset() {
	*x = Cpu{}
	mi := &file_System_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cpu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cpu) ProtoMessage() {}

func (x *Cpu) ProtoReflect() protoreflect.Message {
	mi := &file_System_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cpu.ProtoReflect.Descriptor instead.
func (*Cpu) Descriptor() ([]byte, []int) {
	return file_System_proto_rawDescGZIP(), []int{3}
}

func (x *Cpu) GetUsedCpuPercentage() float32 {
	if x != nil {
		return x.UsedCpuPercentage
	}
	return 0
}

func (x *Cpu) GetFreeCpuPercentage() float32 {
	if x != nil {
		return x.FreeCpuPercentage
	}
	return 0
}

func (x *Cpu) GetCoreCount() int32 {
	if x != nil {
		return x.CoreCount
	}
	return 0
}

func (x *Cpu) GetModelInfo() string {
	if x != nil {
		return x.ModelInfo
	}
	return ""
}

func (x *Cpu) GetIdleTime() float64 {
	if x != nil {
		return x.IdleTime
	}
	return 0
}

func (x *Cpu) GetFrequency() float64 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

// System Utilization type. Cpu, storage and memory utilization.
type Stats struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Cpu            *Cpu                   `protobuf:"bytes,1,opt,name=cpu,proto3" json:"cpu,omitempty"`                       // Cpu Utilization
	StorageDevices []*Resource            `protobuf:"bytes,2,rep,name=storageDevices,proto3" json:"storageDevices,omitempty"` // StorageDevices array of Resource type.
	Memory         *Resource              `protobuf:"bytes,3,opt,name=memory,proto3" json:"memory,omitempty"`                 // RAM Utilization Information
	UpTime         string                 `protobuf:"bytes,4,opt,name=upTime,proto3" json:"upTime,omitempty"`                 // Elapsed time since the device is started.
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Stats) Reset() {
	*x = Stats{}
	mi := &file_System_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stats) ProtoMessage() {}

func (x *Stats) ProtoReflect() protoreflect.Message {
	mi := &file_System_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stats.ProtoReflect.Descriptor instead.
func (*Stats) Descriptor() ([]byte, []int) {
	return file_System_proto_rawDescGZIP(), []int{4}
}

func (x *Stats) GetCpu() *Cpu {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *Stats) GetStorageDevices() []*Resource {
	if x != nil {
		return x.StorageDevices
	}
	return nil
}

func (x *Stats) GetMemory() *Resource {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *Stats) GetUpTime() string {
	if x != nil {
		return x.UpTime
	}
	return ""
}

// System Limits for the EdgeRuntime.
type Limits struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	MaxInstalledApplications int32                  `protobuf:"varint,1,opt,name=maxInstalledApplications,proto3" json:"maxInstalledApplications,omitempty"` // Maximum allowed number of installed edge applications.
	MaxRunningApplications   int32                  `protobuf:"varint,2,opt,name=maxRunningApplications,proto3" json:"maxRunningApplications,omitempty"`     // Maximum allowed number of running edge applications.
	MaxMemoryUsageInGB       float32                `protobuf:"fixed32,3,opt,name=maxMemoryUsageInGB,proto3" json:"maxMemoryUsageInGB,omitempty"`            // Maximum allowed memory usage in Gigabytes.
	MaxStorageUsageInGB      float32                `protobuf:"fixed32,4,opt,name=maxStorageUsageInGB,proto3" json:"maxStorageUsageInGB,omitempty"`          // Maximum allowed disk usage in Gigabytes.
	MaxCpuUsagePerecentage   float32                `protobuf:"fixed32,5,opt,name=maxCpuUsagePerecentage,proto3" json:"maxCpuUsagePerecentage,omitempty"`    // Maximum allowed percentage of CPU usage.
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Limits) Reset() {
	*x = Limits{}
	mi := &file_System_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Limits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Limits) ProtoMessage() {}

func (x *Limits) ProtoReflect() protoreflect.Message {
	mi := &file_System_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Limits.ProtoReflect.Descriptor instead.
func (*Limits) Descriptor() ([]byte, []int) {
	return file_System_proto_rawDescGZIP(), []int{5}
}

func (x *Limits) GetMaxInstalledApplications() int32 {
	if x != nil {
		return x.MaxInstalledApplications
	}
	return 0
}

func (x *Limits) GetMaxRunningApplications() int32 {
	if x != nil {
		return x.MaxRunningApplications
	}
	return 0
}

func (x *Limits) GetMaxMemoryUsageInGB() float32 {
	if x != nil {
		return x.MaxMemoryUsageInGB
	}
	return 0
}

func (x *Limits) GetMaxStorageUsageInGB() float32 {
	if x != nil {
		return x.MaxStorageUsageInGB
	}
	return 0
}

func (x *Limits) GetMaxCpuUsagePerecentage() float32 {
	if x != nil {
		return x.MaxCpuUsagePerecentage
	}
	return 0
}

// LogRequest type, determines the destination path for saving log file.
type LogRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SaveFolderPath string                 `protobuf:"bytes,1,opt,name=saveFolderPath,proto3" json:"saveFolderPath,omitempty"` // Folder path for saving gathered logs.
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_System_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_System_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_System_proto_rawDescGZIP(), []int{6}
}

func (x *LogRequest) GetSaveFolderPath() string {
	if x != nil {
		return x.SaveFolderPath
	}
	return ""
}

// LogResponse type, contains the full path for the collected log archive.
type LogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogPath       string                 `protobuf:"bytes,1,opt,name=logPath,proto3" json:"logPath,omitempty"` // Full file path for collected log archive.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogResponse) Reset() {
	*x = LogResponse{}
	mi := &file_System_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResponse) ProtoMessage() {}

func (x *LogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_System_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogResponse.ProtoReflect.Descriptor instead.
func (*LogResponse) Descriptor() ([]byte, []int) {
	return file_System_proto_rawDescGZIP(), []int{7}
}

func (x *LogResponse) GetLogPath() string {
	if x != nil {
		return x.LogPath
	}
	return ""
}

// Represents the network name of a device. It includes the hostname string, which should adhere to specific format and length requirements as needed by your network or system configuration.
type Hostname struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // The hostname string. Ensure it follows the necessary format and length constraints.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hostname) Reset() {
	*x = Hostname{}
	mi := &file_System_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hostname) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hostname) ProtoMessage() {}

func (x *Hostname) ProtoReflect() protoreflect.Message {
	mi := &file_System_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hostname.ProtoReflect.Descriptor instead.
func (*Hostname) Descriptor() ([]byte, []int) {
	return file_System_proto_rawDescGZIP(), []int{8}
}

func (x *Hostname) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_System_proto protoreflect.FileDescriptor

const file_System_proto_rawDesc = "" +
	"\n" +
	"\fSystem.proto\x12\x1dsiemens.iedge.dmapi.system.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x19google/protobuf/any.proto\"/\n" +
	"\vModelNumber\x12 \n" +
	"\vmodelNumber\x18\x01 \x01(\tR\vmodelNumber\"(\n" +
	"\fFirmwareInfo\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"\xf8\x02\n" +
	"\bResource\x12&\n" +
	"\x0etotalSpaceInGB\x18\x01 \x01(\x02R\x0etotalSpaceInGB\x12$\n" +
	"\rfreeSpaceInGB\x18\x02 \x01(\x02R\rfreeSpaceInGB\x12$\n" +
	"\rusedSpaceInGB\x18\x03 \x01(\x02R\rusedSpaceInGB\x120\n" +
	"\x13percentageFreeSpace\x18\x04 \x01(\x02R\x13percentageFreeSpace\x120\n" +
	"\x13percentageUsedSpace\x18\x05 \x01(\x02R\x13percentageUsedSpace\x12\x1a\n" +
	"\bdiskType\x18\x06 \x01(\tR\bdiskType\x12:\n" +
	"\x18diskTotalReadSectorsInMB\x18\a \x01(\x02R\x18diskTotalReadSectorsInMB\x12<\n" +
	"\x19diskTotalWriteSectorsInMB\x18\b \x01(\x02R\x19diskTotalWriteSectorsInMB\"\xd7\x01\n" +
	"\x03Cpu\x12,\n" +
	"\x11usedCpuPercentage\x18\x01 \x01(\x02R\x11usedCpuPercentage\x12,\n" +
	"\x11freeCpuPercentage\x18\x02 \x01(\x02R\x11freeCpuPercentage\x12\x1c\n" +
	"\tcoreCount\x18\x03 \x01(\x05R\tcoreCount\x12\x1c\n" +
	"\tmodelInfo\x18\x04 \x01(\tR\tmodelInfo\x12\x1a\n" +
	"\bidleTime\x18\x05 \x01(\x01R\bidleTime\x12\x1c\n" +
	"\tfrequency\x18\x06 \x01(\x01R\tfrequency\"\xe7\x01\n" +
	"\x05Stats\x124\n" +
	"\x03cpu\x18\x01 \x01(\v2\".siemens.iedge.dmapi.system.v1.CpuR\x03cpu\x12O\n" +
	"\x0estorageDevices\x18\x02 \x03(\v2'.siemens.iedge.dmapi.system.v1.ResourceR\x0estorageDevices\x12?\n" +
	"\x06memory\x18\x03 \x01(\v2'.siemens.iedge.dmapi.system.v1.ResourceR\x06memory\x12\x16\n" +
	"\x06upTime\x18\x04 \x01(\tR\x06upTime\"\x96\x02\n" +
	"\x06Limits\x12:\n" +
	"\x18maxInstalledApplications\x18\x01 \x01(\x05R\x18maxInstalledApplications\x126\n" +
	"\x16maxRunningApplications\x18\x02 \x01(\x05R\x16maxRunningApplications\x12.\n" +
	"\x12maxMemoryUsageInGB\x18\x03 \x01(\x02R\x12maxMemoryUsageInGB\x120\n" +
	"\x13maxStorageUsageInGB\x18\x04 \x01(\x02R\x13maxStorageUsageInGB\x126\n" +
	"\x16maxCpuUsagePerecentage\x18\x05 \x01(\x02R\x16maxCpuUsagePerecentage\"4\n" +
	"\n" +
	"LogRequest\x12&\n" +
	"\x0esaveFolderPath\x18\x01 \x01(\tR\x0esaveFolderPath\"'\n" +
	"\vLogResponse\x12\x18\n" +
	"\alogPath\x18\x01 \x01(\tR\alogPath\"\x1e\n" +
	"\bHostname\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name2\xab\a\n" +
	"\rSystemService\x12?\n" +
	"\rRestartDevice\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\x0eShutdownDevice\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12;\n" +
	"\tHardReset\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12T\n" +
	"\x0eGetModelNumber\x12\x16.google.protobuf.Empty\x1a*.siemens.iedge.dmapi.system.v1.ModelNumber\x12V\n" +
	"\x0fGetFirmwareInfo\x12\x16.google.protobuf.Empty\x1a+.siemens.iedge.dmapi.system.v1.FirmwareInfo\x12P\n" +
	"\x10GetResourceStats\x12\x16.google.protobuf.Empty\x1a$.siemens.iedge.dmapi.system.v1.Stats\x12J\n" +
	"\tGetLimits\x12\x16.google.protobuf.Empty\x1a%.siemens.iedge.dmapi.system.v1.Limits\x12A\n" +
	"\x11GetCustomSettings\x12\x16.google.protobuf.Empty\x1a\x14.google.protobuf.Any\x12C\n" +
	"\x13ApplyCustomSettings\x12\x14.google.protobuf.Any\x1a\x16.google.protobuf.Empty\x12c\n" +
	"\n" +
	"GetLogFile\x12).siemens.iedge.dmapi.system.v1.LogRequest\x1a*.siemens.iedge.dmapi.system.v1.LogResponse\x12Q\n" +
	"\x0eUpdateHostname\x12'.siemens.iedge.dmapi.system.v1.Hostname\x1a\x16.google.protobuf.Empty\x12N\n" +
	"\vGetHostname\x12\x16.google.protobuf.Empty\x1a'.siemens.iedge.dmapi.system.v1.HostnameB\x1aZ\x18.;siemens_iedge_dmapi_v1b\x06proto3"

var (
	file_System_proto_rawDescOnce sync.Once
	file_System_proto_rawDescData []byte
)

func file_System_proto_rawDescGZIP() []byte {
	file_System_proto_rawDescOnce.Do(func() {
		file_System_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_System_proto_rawDesc), len(file_System_proto_rawDesc)))
	})
	return file_System_proto_rawDescData
}

var file_System_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_System_proto_goTypes = []any{
	(*ModelNumber)(nil),   // 0: siemens.iedge.dmapi.system.v1.ModelNumber
	(*FirmwareInfo)(nil),  // 1: siemens.iedge.dmapi.system.v1.FirmwareInfo
	(*Resource)(nil),      // 2: siemens.iedge.dmapi.system.v1.Resource
	(*Cpu)(nil),           // 3: siemens.iedge.dmapi.system.v1.Cpu
	(*Stats)(nil),         // 4: siemens.iedge.dmapi.system.v1.Stats
	(*Limits)(nil),        // 5: siemens.iedge.dmapi.system.v1.Limits
	(*LogRequest)(nil),    // 6: siemens.iedge.dmapi.system.v1.LogRequest
	(*LogResponse)(nil),   // 7: siemens.iedge.dmapi.system.v1.LogResponse
	(*Hostname)(nil),      // 8: siemens.iedge.dmapi.system.v1.Hostname
	(*emptypb.Empty)(nil), // 9: google.protobuf.Empty
	(*anypb.Any)(nil),     // 10: google.protobuf.Any
}
var file_System_proto_depIdxs = []int32{
	3,  // 0: siemens.iedge.dmapi.system.v1.Stats.cpu:type_name -> siemens.iedge.dmapi.system.v1.Cpu
	2,  // 1: siemens.iedge.dmapi.system.v1.Stats.storageDevices:type_name -> siemens.iedge.dmapi.system.v1.Resource
	2,  // 2: siemens.iedge.dmapi.system.v1.Stats.memory:type_name -> siemens.iedge.dmapi.system.v1.Resource
	9,  // 3: siemens.iedge.dmapi.system.v1.SystemService.RestartDevice:input_type -> google.protobuf.Empty
	9,  // 4: siemens.iedge.dmapi.system.v1.SystemService.ShutdownDevice:input_type -> google.protobuf.Empty
	9,  // 5: siemens.iedge.dmapi.system.v1.SystemService.HardReset:input_type -> google.protobuf.Empty
	9,  // 6: siemens.iedge.dmapi.system.v1.SystemService.GetModelNumber:input_type -> google.protobuf.Empty
	9,  // 7: siemens.iedge.dmapi.system.v1.SystemService.GetFirmwareInfo:input_type -> google.protobuf.Empty
	9,  // 8: siemens.iedge.dmapi.system.v1.SystemService.GetResourceStats:input_type -> google.protobuf.Empty
	9,  // 9: siemens.iedge.dmapi.system.v1.SystemService.GetLimits:input_type -> google.protobuf.Empty
	9,  // 10: siemens.iedge.dmapi.system.v1.SystemService.GetCustomSettings:input_type -> google.protobuf.Empty
	10, // 11: siemens.iedge.dmapi.system.v1.SystemService.ApplyCustomSettings:input_type -> google.protobuf.Any
	6,  // 12: siemens.iedge.dmapi.system.v1.SystemService.GetLogFile:input_type -> siemens.iedge.dmapi.system.v1.LogRequest
	8,  // 13: siemens.iedge.dmapi.system.v1.SystemService.UpdateHostname:input_type -> siemens.iedge.dmapi.system.v1.Hostname
	9,  // 14: siemens.iedge.dmapi.system.v1.SystemService.GetHostname:input_type -> google.protobuf.Empty
	9,  // 15: siemens.iedge.dmapi.system.v1.SystemService.RestartDevice:output_type -> google.protobuf.Empty
	9,  // 16: siemens.iedge.dmapi.system.v1.SystemService.ShutdownDevice:output_type -> google.protobuf.Empty
	9,  // 17: siemens.iedge.dmapi.system.v1.SystemService.HardReset:output_type -> google.protobuf.Empty
	0,  // 18: siemens.iedge.dmapi.system.v1.SystemService.GetModelNumber:output_type -> siemens.iedge.dmapi.system.v1.ModelNumber
	1,  // 19: siemens.iedge.dmapi.system.v1.SystemService.GetFirmwareInfo:output_type -> siemens.iedge.dmapi.system.v1.FirmwareInfo
	4,  // 20: siemens.iedge.dmapi.system.v1.SystemService.GetResourceStats:output_type -> siemens.iedge.dmapi.system.v1.Stats
	5,  // 21: siemens.iedge.dmapi.system.v1.SystemService.GetLimits:output_type -> siemens.iedge.dmapi.system.v1.Limits
	10, // 22: siemens.iedge.dmapi.system.v1.SystemService.GetCustomSettings:output_type -> google.protobuf.Any
	9,  // 23: siemens.iedge.dmapi.system.v1.SystemService.ApplyCustomSettings:output_type -> google.protobuf.Empty
	7,  // 24: siemens.iedge.dmapi.system.v1.SystemService.GetLogFile:output_type -> siemens.iedge.dmapi.system.v1.LogResponse
	9,  // 25: siemens.iedge.dmapi.system.v1.SystemService.UpdateHostname:output_type -> google.protobuf.Empty
	8,  // 26: siemens.iedge.dmapi.system.v1.SystemService.GetHostname:output_type -> siemens.iedge.dmapi.system.v1.Hostname
	15, // [15:27] is the sub-list for method output_type
	3,  // [3:15] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_System_proto_init() }
func file_System_proto_init() {
	if File_System_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_System_proto_rawDesc), len(file_System_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_System_proto_goTypes,
		DependencyIndexes: file_System_proto_depIdxs,
		MessageInfos:      file_System_proto_msgTypes,
	}.Build()
	File_System_proto = out.File
	file_System_proto_goTypes = nil
	file_System_proto_depIdxs = nil
}
